apiVersion: eventing.knative.dev/v1alpha1
kind: Channel
metadata:
  name: blue
spec: {}

---
# TODO add one more subscription
apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: j-cloudevent-logger
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: blue
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: j-cloudevent-logger
---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: j-cloudevent-logger
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: kameshsampath/j-cloudevent-logger:0.0.1